baseURL = "https://nosignal.zone"
languageCode = "en-us"
title = "*** No Signal ***"
buildFuture = true
disableHugoGeneratorInject = true
enableGitInfo = true
[params]
	tagline = "Media for a Burning World"
